# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f5f7b2f8db9f1862267b43ae9155caddcae29e1cc83fc83f8c2ccac39a86524a60b3c6f1af367090edf565bb95eb36ace4382946c31d948df7d581b8e3b5643

test:
  secret_key_base: d7d6ab695cc113d50f1cc6405a8e3649e5bf0db7149ee1fbf9b519fe6e77d24b31aca26f292272d3725b3a6215c9f7e88554b91ddeb874eaacd68d3b2f9fe8a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
